name: test

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            #----------------------------------------------
            #       check-out repo and set-up python
            #----------------------------------------------
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13.1'
            #----------------------------------------------
            #  -----  install & configure poetry  -----
            #----------------------------------------------
            - name: Install Poetry
              uses: snok/install-poetry@v1
            #----------------------------------------------
            #  -----  install dependencies  -----  
            #----------------------------------------------
            - name: Install dependencies
              run: poetry install --no-interaction --no-root
            #----------------------------------------------
            #  -----  run test suite  -----  
            #----------------------------------------------
            - name: Run tests
              run: poetry run pytest tests -v
